export { default as Hero } from "./Hero";
export { default as Footer } from "./Footer";
export { default as PopularServices } from "./PopularProduct";
export { default as CustomerReviews } from "./CustomerReviews";
export { default as PopularProduct } from "./PopularProduct";
export { default as Services } from "./Services";
export { default as Subscribe } from "./Subscribe";
export { default as SuperQuality } from "./SuperQuality";
export { default as SpecialOffer } from "./SpecialOffer";
